import { Component,inject,signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { Api } from '../core/api';
import { User,message } from '../core/types';
@Component({imports:[FormsModule],template:`<div class="section-heading"><h2>Customers</h2><button class="small" (click)="edit()">Add customer</button></div>@if(error()){<p role="alert" class="alert error">{{error()}}</p>}@if(notice()){<p role="status" class="alert success">{{notice()}}</p>}
@if(loading()){<p class="empty">Loading customers…</p>}@else{<div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>@for(u of items();track u.id){<tr><td>{{u.name}}</td><td>{{u.email}}</td><td>{{u.active?'Active':'Inactive'}}</td><td class="table-actions"><button class="text-button" (click)="edit(u)" [disabled]="busy()">Edit</button><button class="text-button danger" (click)="remove(u)" [disabled]="busy()">Delete</button></td></tr>}@empty{<tr><td colspan="4">No customers yet.</td></tr>}</tbody></table></div>}
@if(open()){<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="customer-form-title"><h2 id="customer-form-title">{{id?'Edit customer':'Add customer'}}</h2><form (ngSubmit)="save()" #f="ngForm"><label>Name<input name="name" [(ngModel)]="form.name" required maxlength="100"></label><label>Email<input type="email" name="email" [(ngModel)]="form.email" required email maxlength="150"></label><label>{{id?'New password (optional)':'Password'}}<input type="password" name="password" [(ngModel)]="form.password" [required]="!id" minlength="8" autocomplete="new-password"></label>@if(id){<label class="checkbox"><input type="checkbox" name="active" [(ngModel)]="form.active"> Active account</label>}@if(formError()){<p role="alert" class="alert error">{{formError()}}</p>}<div class="actions"><button type="button" class="secondary" (click)="open.set(false)" [disabled]="busy()">Cancel</button><button [disabled]="busy()||f.invalid">{{busy()?'Saving…':'Save customer'}}</button></div></form></section></div>}`})
export class CustomerManagement{private api=inject(Api);items=signal<User[]>([]);loading=signal(true);busy=signal(false);error=signal('');notice=signal('');formError=signal('');open=signal(false);id=0;form={name:'',email:'',password:'',active:true};constructor(){void this.load();}async load(){try{this.items.set((await firstValueFrom(this.api.get<User[]>('/customers'))).data);}catch(e){this.error.set(message(e));}finally{this.loading.set(false);}}
edit(u?:User){this.id=u?.id||0;this.form={name:u?.name||'',email:u?.email||'',password:'',active:u?!!u.active:true};this.formError.set('');this.open.set(true);}
async save(){if(this.busy())return;this.busy.set(true);this.formError.set('');try{const body:Record<string,unknown>={name:this.form.name,email:this.form.email};if(this.form.password)body['password']=this.form.password;if(this.id)body['active']=this.form.active;await firstValueFrom(this.id?this.api.patch('/customers/'+this.id,body):this.api.post('/customers',body));this.open.set(false);this.notice.set('Customer saved.');await this.load();}catch(e){this.formError.set(message(e));}finally{this.busy.set(false);}}
async remove(u:User){if(this.busy()||!confirm('Delete '+u.name+'? Customers with rental history will be deactivated.'))return;this.busy.set(true);this.error.set('');try{this.notice.set((await firstValueFrom(this.api.delete('/customers/'+u.id))).data.message);await this.load();}catch(e){this.error.set(message(e));}finally{this.busy.set(false);}}
}
